# コンテキストパス指定
server:
  servlet:
    contextPath: /sv_linebot_test

#--------------------------
# LINEbot設定
#--------------------------
line.bot:
  channel-token: ${LINE_BOT_CHANNEL_TOKEN}
  channel-secret: ${LINE_BOT_CHANNEL_SECRET}
  handler.path: /callback

